name: Daily Job Fetch

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 8am BST (7am UTC)
  workflow_dispatch:      # Allows manual runs

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run job fetch script
        run: node fetchJobs.js

      - name: Commit and push if jobs.json changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/jobs.json
          git commit -m "Daily job fetch update" || echo "No changes to commit"
          git push
